# Generated by Django 4.2 on 2024-06-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_rename_is_staff_appuser_is_admin_alter_appuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
